import random

def generate_keys(p, g):
    a = random.randint(2, p-2)
    A = pow(g, a, p)
    return (a, A)

def generate_shared_secret(a, B, p):
    s = pow(B, a, p)
    return s

# =========================

p = 23
g = 5

# Alice generates her keys
a, A = generate_keys(p, g)

# Bob generates his keys
b, B = generate_keys(p, g)

# Alice andBob exchange their public keys
s1 = generate_shared_secret(a, B, p)
s2 = generate_shared_secret(b, A, p)

# The shared secret keys generated by Alice and Bob should be the same
assert s1 == s2
print("Shared secret key:", s1)